"""
training_data.py
All training examples for the message categorizer.
Categories: order, inquiry, complaint, feedback, invalid
"""
import pandas as pd


def get_training_data() -> pd.DataFrame:
    """Return a DataFrame with columns ['message', 'category'] for model training."""

    order_examples = [
        "I want to order a large pizza",
        "Please sign me up for the premium plan",
        "I'd like to schedule a service appointment",
        "Add this to my cart",
        "I want to purchase the new iPhone",
        "Book me a table for two at 7pm",
        "I need to upgrade my subscription",
        "Place an order for delivery",
        "I want to buy this product",
        "Add this to my order",
        "I need to change my order",
        "Please confirm my purchase",
        "I'd like to pre-order the new model",
        "Process my payment",
        "I want to place a bulk order",
        "Please ship this to my home address",
        "I'd like to proceed with the checkout",
        "Please bill my credit card",
        "I want to schedule a delivery for tomorrow",
        "Please add this item to my existing order",
        "I need to place a corporate order",
        "Please process this as a gift order",
        "I want to order a replacement part",
        "Please send me a quote for 100 units",
        "I'd like to make a special order",
        "I need 5 kg of basmati rice",
        "Send me 2 packets of butter",
        "I want to order 3 boxes of sweets for Diwali",
        "Please deliver 10 bottles of water",
        "I need to place an order for office supplies",
        "Can you send me the combo meal?",
        "I want two chocolate cakes for the party",
        "Urgent: Can I get this delivered by tomorrow?",
        "I'm so excited to place my first order with you!",
        "I'd love to order your premium package, it looks amazing!",
        "I'm really disappointed with my last order, but I'd like to give it another try.",
        "This is exactly what I've been looking for! How do I order?",
        "I'd love to order another one of these amazing products!",
        "I want to reorder the same thing as last time",
        "Please cancel my previous order and place a new one",
    ]

    inquiry_examples = [
        "What are your business hours?",
        "When will my order be delivered?",
        "How can I track my package?",
        "Do you offer international shipping?",
        "What payment methods do you accept?",
        "Is this item in stock?",
        "Can I change my delivery address?",
        "What's your return policy?",
        "How do I cancel my order?",
        "Are there any discounts available?",
        "What's included in the basic package?",
        "How do I create an account?",
        "Can I get a refund?",
        "What's the warranty on this product?",
        "Do you have a physical store?",
        "How do I contact customer service?",
        "What's the estimated delivery time?",
        "Can I modify my order?",
        "What's your privacy policy?",
        "How do I reset my password?",
        "How to pay my bill?",
        "How can I pay my bill online?",
        "What are the different ways to pay my bill?",
        "When is my bill due?",
        "Can you explain the charges on my bill?",
        "How do I get a copy of my bill?",
        "Is there a late fee for bill payments?",
        "How do I update my payment method?",
        "What's the minimum payment required?",
        "How do I get a receipt for my payment?",
        "Why was my payment declined?",
        "Can I pay my bill in installments?",
        "What's the billing cycle?",
        "How do I change my billing address?",
        "How do I dispute a charge on my bill?",
        "How do I check my payment history?",
        "What happens if I miss a payment?",
        "How much does this cost?",
        "What is the price of your product?",
        "Could you tell me more about this product?",
        "Would it be possible to get a discount?",
        "Might you have this in a different color?",
        "I was wondering about your return process?",
        "Can you explain how the warranty works?",
        "What's the difference between the basic and premium plans?",
        "Could you clarify your shipping policy?",
        "I'd like to know more about your services",
        "What are the terms and conditions?",
        "How does your loyalty program work?",
        "Do you deliver on Sundays?",
        "What is the delivery charge for my area?",
        "Do you have any vegan options?",
        "Can I visit your shop tomorrow?",
        "I'm not sure I understand how this works, can you explain?",
        "Quick question: What's your return policy?",
        "I'm really interested in your service, can you tell me more?",
        "How does this compare to your other products?",
        "I'm a bit confused about your pricing, can you clarify?",
    ]

    complaint_examples = [
        "I absolutely hate this service, it's the worst!",
        "This is completely unacceptable, I'm very disappointed.",
        "I'm extremely frustrated with your terrible service.",
        "The quality is absolutely awful, never again!",
        "I'm so angry about this horrible experience.",
        "This is ridiculous, I can't believe how bad this is.",
        "I'm extremely dissatisfied with your service.",
        "This is the worst experience I've ever had.",
        "My product arrived damaged and broken",
        "The delivery was late by 3 days",
        "I received the wrong item in my order",
        "The food was cold when it arrived",
        "Your customer support is terrible",
        "I've been waiting for a refund for 2 weeks",
        "The product stopped working after one day",
        "This is not what I ordered at all",
        "I love your products but the delivery was late.",
        "Great quality but way too expensive for what you get.",
        "The customer service was excellent but the product broke quickly.",
        "Oh great, another day without my order.",
        "Wow, I'm so impressed with how late this is.",
        "Because what I wanted was a broken product, thanks!",
        "I'm sorry to say I'm quite disappointed with my purchase.",
        "I was really hoping for better quality than this.",
        "This isn't quite what I was expecting, to be honest.",
        "I need this fixed immediately, this is completely unacceptable!",
        "I'm so sorry, but I think there's been a mistake with my order.",
        "I hate to complain, but I'm not satisfied with my purchase.",
        "I had such high hopes for this, but I'm really disappointed.",
        "This doesn't live up to the hype at all, I want my money back.",
        "I've had nothing but problems with this service!",
        "This is the third time I've had to contact support, fix this now!",
        "I'm absolutely furious about the poor service I received!",
        "This is completely unacceptable and needs to be fixed immediately!",
        "I'm furious about how bad this is.",
        "The packaging was torn and the product was spoiled",
        "You sent me expired goods, this is unacceptable",
        "My order is missing 2 items",
        "The delivery boy was very rude",
        "I asked for no onions but the order has onions",
    ]

    feedback_examples = [
        "I absolutely love your service, it's amazing!",
        "This is the best experience I've ever had, thank you!",
        "Your service is outstanding, can't wait to recommend it!",
        "I'm so grateful for your excellent service!",
        "Thank you for the wonderful experience.",
        "I'm so happy with my purchase!",
        "Great product, really impressed with the quality.",
        "The delivery was super fast, thanks!",
        "Your team is very helpful and friendly.",
        "I've been a customer for years and never been disappointed.",
        "Keep up the great work!",
        "Excellent packaging, very professional.",
        "Best price in the market, will order again.",
        "The customer service rep was very patient and helpful.",
        "Loved the new menu items, especially the paneer wrap.",
        "Your app is very easy to use.",
        "I recommended your service to all my friends.",
        "The quality has improved a lot since last year.",
        "Everything was perfectly packed and on time.",
        "Wonderful experience, 5 stars!",
        "Thank you so much for your help, I really appreciate it!",
        "You've made me a customer for life with this service!",
        "I'm really impressed with what I've seen so far!",
        "I can't wait to try out your service, it looks amazing!",
        "I'm absolutely thrilled with my purchase!",
        "This is exactly what I was looking for, great job!",
    ]

    invalid_examples = [
        "asdfghjkl qwertyuiop",
        "12345 67890",
        "qazwsx edcrfv tgb yhn ujm",
        "asd asd asd asd asd",
        "123 testing 123 testing",
        "test test test test",
        "abc abc abc abc",
        "hello world",
        "hi",
        "ok",
        "...",
        "????",
        "!!!!!",
        "lol random stuff here",
        "just typing some random text",
        "kdsjfhskdjfh",
        "aaaaaaaaaa",
        "zzzzzzzzzz",
        "hmmm",
        "bruh",
        "yo",
        "hey",
        "k",
        "nm",
        "idk",
        "lmao",
        "nothing really",
        "random words that don't make sense together",
        "this is not a valid message please ignore",
        "just some random text",
    ]

    data = []
    for msg in order_examples:
        data.append({"message": msg, "category": "order"})
    for msg in inquiry_examples:
        data.append({"message": msg, "category": "inquiry"})
    for msg in complaint_examples:
        data.append({"message": msg, "category": "complaint"})
    for msg in feedback_examples:
        data.append({"message": msg, "category": "feedback"})
    for msg in invalid_examples:
        data.append({"message": msg, "category": "invalid"})

    return pd.DataFrame(data)
